services:
  - type: web
    name: vedavayu-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADDITIONAL_ORIGINS
        value: "*"
